common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: im1coolguy

development:
  <<: *common
  database: vmMobile

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: im1coolguy
  database: vmMobile_test
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: im1coolguy
  database: vmServer_production
  timeout: 5000
